FROM nginx:alpine

#conf
COPY /conf/nginx.conf /etc/nginx/nginx.conf

#content, comment out the ones you dont need
COPY . /usr/share/nginx/html

#COPY ./*.html /user/share/nginx/html
#COPY ./*.css /user/share/nginx/html
#COPY ./*.png /user/share/nginx/html
#COPY ./*.js /user/share/nginx/html

